version:                "3"
services:
  acf:
      image:            acf-dev:latest
      volumes:
        - ./notebooks:/home/jovyan/work
        - ./data:/home/jovyan/work/data
        - ./out:/home/jovyan/work/out
        - ./sim:/home/jovyan/work/sim
        - ./mc:/home/jovyan/work/mc
      ports:
        - 1167:1167
      container_name:   acf