---
title: "Intervention"
author: "Chu-Chang Ku"
date: "4/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidybayes)

theme_set(theme_tidybayes() + theme_bw())

```


## Info. intervention samples
```{r, echo=FALSE, message=FALSE, warning=FALSE}

sims <- read_csv(here::here("out", "dy", "Runs_Intv.csv")) %>% 
  mutate(Year = Time + 0.5)


dt <- diff(sort(unique(sims$Time)))[1]

sims_acc <- sims %>% 
  mutate(
    Year = Time + 0.5,
    Inc = Pop * IncR * dt,
    Mor = Pop * MorR * dt
  ) %>% 
  select(Year, Inc, Mor, Key, Scenario) %>% 
  group_by(Key, Scenario) %>% 
  arrange(Year) %>% 
  mutate(
    across(c(Inc, Mor), cumsum)
  ) %>% 
  ungroup()


scenario0 <- "(0)Baseline"

sims_acc0 <- sims_acc %>% 
  filter(Scenario == scenario0) %>% 
  select(- Scenario) %>% 
  rename(Mor0 = Mor, Inc0 = Inc)

sims_acc1 <- sims_acc %>% filter(Scenario != scenario0)


```

- Sample size:  `r length(unique(sims$Key))`
- Time range: `r range(sims$Time)``

## Intervention effects

```{r, echo=FALSE, message=FALSE, warning=FALSE}

sims %>% 
  group_by(Year, Scenario) %>% 
  summarise(across(c(IncR, MorR), mean)) %>% 
  pivot_longer(c(MorR, IncR), names_to = "Index") %>%
  ggplot() +
  geom_line(aes(x = Year, y = value, colour = Scenario)) + 
  scale_y_continuous("per 100 000", labels = scales::number_format(scale = 1e5)) +
  scale_x_continuous("Year", breaks = seq(2020, 2030, 5)) +
  expand_limits(y = 0) +
  facet_wrap(.~Index, scale = "free_y")

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

sims_acc1 %>% 
  left_join(sims_acc0) %>% 
  group_by(Year, Scenario) %>%
  mutate(
    PrAccInc = (1 - Inc / Inc0),
    PrAccMor = (1 - Mor / Mor0)
  ) %>% 
  summarise(
    across(c(PrAccInc, PrAccMor), mean)
  ) %>% 
  ungroup() %>% 
  pivot_longer(c(PrAccInc, PrAccMor)) %>% 
  ggplot() +
  geom_line(aes(x = Year, y = value, colour = Scenario)) +
  facet_grid(.~name)


```



